name: ai-sdk

on:
  workflow_dispatch: {}
  push:
    branches:
        - main
        - development
  schedule:
    - cron: "*/5 * * * *"
jobs:
  flat:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.coindesk.com/v2/bpi/currentprice.json
          downloaded_filename: data.json
  ai-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Data
        id: mergeData
        uses: 0research/ai-sdk@main
        with:
          merge_strategy: overwrite
          json1: json1/
          json2: json2/
      - name: Write Json 1
        uses: jsdaniell/create-json@1.1.2
        with: 
          name: "json1"
          json: ${{ steps.mergeData.outputs.merge_data_1 }}

      
