name: ai-sdk

on:
  workflow_dispatch: {}
  push:
    branches:
        - main
        - development
  schedule:
    - cron: "*/5 * * * *"
jobs:
  ai-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data 1
        uses: githubocto/flat@v3
        with:
          http_url: https://api.coindesk.com/v2/bpi/currentprice.json
          downloaded_filename: data1.json
      - name: Fetch data 1
        uses: githubocto/flat@v3
        with:
          http_url: https://free.currconv.com/api/v7/convert?q=USD_PHP&compact=ultra&apiKey=4709550d97d6056b11e5
          downloaded_filename: data2.json
      - name: Merge Data
        id: mergeData
        uses: 0research/ai-sdk@main
        with:
          merge_strategy: overwrite
          json1: data1.json
          json2: data2.json
      - name: Test Print JSON
        run: echo ${{ steps.mergeData.outputs.merged_json_1 }}
      - name: Write Json 1
        uses: jsdaniell/create-json@1.1.2
        with: 
          name: "merged_json_1.json"
          json: ${{ steps.mergeData.outputs.merged_json_1 }}
      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions

      
