on:
  workflow_dispatch:
    inputs:
        input1:
          description: 'Log level'     
          required: true
          default: 'warning'
        input2:
          description: 'Test scenario tags'
  push:
    paths:
      - .github/workflows/flat.yml
  schedule:
    - cron: "*/5 * * * *"
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.coindesk.com/v2/bpi/currentprice.json
          downloaded_filename: data.json
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
